name: RDP

on:
  workflow_dispatch:

jobs:
  debian-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Set up Debian RDP Environment
        run: |
          sudo apt update -y && sudo apt install -y xrdp xfce4 xfce4-goodies curl
          sudo systemctl enable xrdp && sudo systemctl start xrdp
          sudo useradd -m RDP && echo "RDP:Password123!" | sudo chpasswd
          echo "RDP user: RDP | Password: Password123!"
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
      - name: Connect to Tailscale
        run: |
          sudo tailscale up --authkey=tskey-client-tskey-auth-kM5kDgACNa11CNTRL-7yyhiarewfc1kj8tjD2vgckqNZsR2nJAA --hostname=gh-runner-${{ github.run_id }}
          echo "Tailscale IP: $(tailscale ip -4)"
      - name: Keep Alive
        run: |
          while true; do echo "[$(date)] RDP Active"; sleep 300; done


